# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./platform
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 3000:3000
    - 4000:4000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000
    - SOCKET_IO_PORT=4000
  command:
    sh -c 'npm i && npm run build --prefix ./web'